name: Regista Engine Automation
on:
  schedule:
    # Perşembe, Cuma ve Cumartesi günleri saat 09:00'da çalışır
    - cron: '0 9 * * 4,5,6' 
  workflow_dispatch: # Manuel tetikleme her zaman açık kalsın

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install
        run: pip install -r requirements.txt
      - name: Run
        env:
          SB_URL: ${{ secrets.SB_URL }}
          SB_KEY: ${{ secrets.SB_KEY }}
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: python main.py
